Added first unit tests and bug fixes
apfong/nginx-configparser pull request #1
Opened 2017-01-16 22:48 UTC by apfong

Fixed mismatched curly brackets and nested blocks.

2017-01-16 23:20 UTC, kfrankc commented
`d3405da` should be split into two commits. One for fixing the parser for unpaired and nested bracket, and one for the unit tests.

2017-01-16 23:22 UTC, kfrankc commented on config_parser.cc
> +        if (c == ' ' || c == '\t' || c == '\n' ||
This is very nice, I did not even notice the extra condition in the `if` statements

2017-01-16 23:27 UTC, kfrankc requested changes
Added two comment on the test fixtures

2017-01-16 23:27 UTC, kfrankc commented on config_parser_test.cc
> +  EXPECT_TRUE(ParseString("user  www www;\n\
These long strings could be put into files, making it easier to view + to test. Just a future practice

2017-01-16 23:27 UTC, kfrankc commented on config_parser_test.cc
> +  EXPECT_TRUE(ParseString("# hello world\n server { listen 80; }"));
I suggest adding comments on failure: ex. `<< "Error: failed to detect comment";` on these tests for more clarity when they are fired.

2017-01-17 00:03 UTC, KyCodeHuynh requested changes
Looks great overall, but it looks like some test input is missing.

2017-01-17 00:03 UTC, KyCodeHuynh commented on .gitignore
> +# From http://stackoverflow.com/questions/5711120/gitignore-without-binary-files
A very useful gitignore!

2017-01-17 00:03 UTC, KyCodeHuynh commented on config_parser_test.cc
> +  bool success = parser.Parse("vhosts_config", &out_config);
Where is this `vhosts_config` file? I know your gitignore above ignores files without extensions, but this test doesn't appear to be repeatable without the config files used by each test?

2017-01-17 00:03 UTC, KyCodeHuynh commented on config_parser_test.cc
> +  bool success = parser.Parse("listen_default_config", &out_config);
[Similar to above](https://github.com/apfong/nginx-configparser/pull/1/files#r96323085)

2017-01-17 00:31 UTC, apfong commented on config_parser_test.cc
> +  bool success = parser.Parse("vhosts_config", &out_config);
Fixed, see [commit](https://github.com/apfong/nginx-configparser/pull/1/commits/af237643145f3b6c5b8b4f7b146b119cde13021a)

2017-01-17 00:31 UTC, apfong commented on config_parser_test.cc
> +  bool success = parser.Parse("listen_default_config", &out_config);
[Same commit as previous comment](https://github.com/apfong/nginx-configparser/pull/1#discussion_r96325335)

2017-01-17 00:32 UTC, apfong commented on config_parser_test.cc
> +  EXPECT_TRUE(ParseString("user  www www;\n\
[Got it](https://github.com/apfong/nginx-configparser/pull/1/commits/435bd2d8a54da461ee5c0ff4656ec46b3a755ea2)

2017-01-17 00:32 UTC, apfong commented on config_parser_test.cc
> +  EXPECT_TRUE(ParseString("# hello world\n server { listen 80; }"));
[Error messages are in](https://github.com/apfong/nginx-configparser/pull/1/commits/435bd2d8a54da461ee5c0ff4656ec46b3a755ea2)

2017-01-17 00:37 UTC, KyCodeHuynh commented on config_parser_test.cc
> +  bool success = parser.Parse("vhosts_config", &out_config);
Awesome, thank you!

2017-01-17 00:39 UTC, KyCodeHuynh approved these changes
Great work! LGTM now. 👍

2017-01-17 00:42 UTC, kfrankc approved these changes
Looks good!

2017-01-17 00:43 UTC, merged